version: '3'

services:

  mongodb:
    container_name: dart_mongodb
    hostname: mongodb
    image: mongo:4.4.0
    ports:
      - 27017:27017
      - 28017:28017
    environment:
      # - MONGO_INITDB_DATABASE=transport
      # - MONGO_INITDB_ROOT_USERNAME=master
      # - MONGO_INITDB_ROOT_PASSWORD=letmein
      - AUTH=no
    networks:
      - mongonet

  mongo-admin:
    container_name: dart_mongodb-admin
    depends_on:
      - mongodb
    hostname: mongo-admin
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    networks:
      - mongonet
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017

networks:
  mongonet:
    driver: bridge
